DROP DATABASE STUDENT_MANAGEMENT;
GO
CREATE DATABASE STUDENT_MANAGEMENT;
GO
USE STUDENT_MANAGEMENT;
GO

CREATE TABLE STUDENT
(
    IDSTU CHAR(8),
    NAME NVARCHAR(40),
    GRADE varchar(10),
    BIRTHDAY DATE,
    ADDRESS NVARCHAR(100),
    NOTES NVARCHAR(100)

        CONSTRAINT PK_STUDENT PRIMARY KEY (IDSTU)
)

CREATE TABLE COURSE
(
    IDCOURSE CHAR(8),
    NAME NVARCHAR(40),
    LECTURE NVARCHAR(40),
    YEAR varchar(10),
    SEMESTER INT CHECK (SEMESTER >= 1 AND SEMESTER <= 3),
    NOTES NVARCHAR(100),
    CREDIT INT CHECK (CREDIT >= 0 AND CREDIT <= 20),

    CONSTRAINT PK_COURSE PRIMARY KEY (IDCOURSE, LECTURE, YEAR, SEMESTER)
)

CREATE TABLE TAKEPARTINCOURSE
(
    STUID CHAR(8),
    COURSEID CHAR(8),
    LECTURE NVARCHAR(40),
    YEAR varchar(10),
    SEMESTER INT CHECK (SEMESTER >= 1 AND SEMESTER <= 3),
    SCORE FLOAT CHECK (SCORE >= 0 AND SCORE <= 10)

        CONSTRAINT PK_TAKEPARTINCOURSE PRIMARY KEY (STUID, COURSEID, LECTURE, YEAR, SEMESTER)
)

CREATE TABLE ACCOUNT
(
    USERNAME NVARCHAR(40),
    PASSWORD NVARCHAR(40),
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (USERNAME)
)

CREATE TABLE MANAGESTUDENT
(
    USERNAME NVARCHAR(40),
    IDSTU CHAR(8),
    CONSTRAINT PK_MANAGESTUDENT PRIMARY KEY (USERNAME, IDSTU)
)

CREATE TABLE MANAGECOURSE
(
    USERNAME NVARCHAR(40),
    COURSEID CHAR(8),
    LECTURE NVARCHAR(40),
    YEAR varchar(10),
    SEMESTER INT CHECK (SEMESTER >= 1 AND SEMESTER <= 3),
    CONSTRAINT PK_MANAGECOURSE PRIMARY KEY (USERNAME, COURSEID, LECTURE, YEAR, SEMESTER)
)
ALTER TABLE TAKEPARTINCOURSE ADD
    CONSTRAINT FK_TAKEPARTINCOURSE_STUDENT FOREIGN KEY (STUID) REFERENCES STUDENT(IDSTU),
    CONSTRAINT FK_TAKEPARTINCOURSE_COURSE FOREIGN KEY (COURSEID, LECTURE, YEAR, SEMESTER) REFERENCES COURSE(IDCOURSE, LECTURE, YEAR, SEMESTER)

ALTER TABLE MANAGESTUDENT ADD
    CONSTRAINT FK_MANAGESTUDENT_ACCOUNT FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME),
    CONSTRAINT FK_MANAGESTUDENT_STUDENT FOREIGN KEY (IDSTU) REFERENCES STUDENT(IDSTU)

ALTER TABLE MANAGECOURSE ADD
    CONSTRAINT FK_MANAGECOURSE_ACCOUNT FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME),
    CONSTRAINT FK_MANAGECOURSE_COURSE FOREIGN KEY (COURSEID, LECTURE, YEAR, SEMESTER) REFERENCES COURSE(IDCOURSE, LECTURE, YEAR, SEMESTER)

INSERT INTO STUDENT VALUES ('21120553', N'Trần Thái Tân', 'K21', '2003-08-30', N'Bạc Liêu', N'Học CNTT')
INSERT INTO STUDENT VALUES ('21120554', N'Nguyễn Văn B', 'K22', '1999-01-01', N'Đà Nẵng', N'Học CNTT')
INSERT INTO STUDENT VALUES ('21120555', N'Nguyễn Văn C', 'K21', '1999-01-01', N'Đà Nẵng', N'Học CNTT')
INSERT INTO STUDENT VALUES ('21120556', N'Nguyễn Văn D', 'K22', '1999-01-01', N'Đà Nẵng', N'Học CNTT')

INSERT INTO COURSE VALUES ('CSC10001', N'Nhập môn lập trình', N'Nguyễn Văn A', '2020-2021', 1, N'Cơ sở ngành', 4)
INSERT INTO COURSE VALUES ('CSC10002', N'Kỹ thuật lập trình', N'Nguyễn Văn A', '2020-2021', 2, N'Cơ sở ngành', 4)
INSERT INTO COURSE VALUES ('CSC10003', N'Cấu trúc dữ liệu & giải thuật', N'Nguyễn Văn A', '2022-2023', 1, N'Cơ sở ngành', 4)
INSERT INTO COURSE VALUES ('CSC10004', N'Lập trình hướng đối tươợng', N'Nguyễn Văn A', '2022-2023', 2, N'Cơ sở ngành', 4)

INSERT INTO TAKEPARTINCOURSE VALUES ('21120553', 'CSC10001', N'Nguyễn Văn A', '2020-2021', 1, 10)
INSERT INTO TAKEPARTINCOURSE VALUES ('21120553', 'CSC10002', N'Nguyễn Văn A', '2020-2021', 2, 9)
INSERT INTO TAKEPARTINCOURSE VALUES ('21120553', 'CSC10003', N'Nguyễn Văn A', '2022-2023', 1, 8)
INSERT INTO TAKEPARTINCOURSE VALUES ('21120553', 'CSC10004', N'Nguyễn Văn A', '2022-2023', 2, NULL)

INSERT INTO ACCOUNT VALUES (N'admin', 'pLReejqzjMX9Q7WbxYDe1xg/TZo=')

INSERT INTO MANAGESTUDENT VALUES (N'admin', '21120553')
INSERT INTO MANAGESTUDENT VALUES (N'admin', '21120554')
INSERT INTO MANAGESTUDENT VALUES (N'admin', '21120555')

INSERT INTO MANAGECOURSE VALUES (N'admin', 'CSC10001', N'Nguyễn Văn A', '2020-2021', 1)

SELECT * FROM MANAGECOURSE
SELECT * FROM MANAGESTUDENT